import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/atracoes.module.css'
import Header from './components/header'

export default function Home() {
  return (
    <>
      <Head>
        <title>AfroPunk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <section className={styles.section}>
            <div className={styles.top}>
                <div id={styles.linhatop}></div>
                <div className={styles.toptext}>
                    <div className={styles.toptexta}>
                        <a href="/">Voltar</a>
                    </div>
                    <div className={styles.toptexth1}>
                        <h1>Atrações</h1>                        
                    </div>
                </div>
                <div id={styles.linhabottom}></div>
            </div>
            <div className={styles.botton}>
                <div className={styles.column}>
                    <h2>17 novembro</h2>
                    <div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>                        
                    </div>
                    <div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>                        
                    </div>
                    <div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>                        
                    </div>
                    <div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>                        
                    </div>
                </div>
                <div id={styles.linhacenter}></div>
                <div className={styles.column}>
                    <h2>18 novembro</h2>
                    <div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>                        
                    </div>
                    <div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>                        
                    </div>
                    <div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>                        
                    </div>
                    <div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>
                        <div>
                            <p></p>
                            <h3></h3>
                        </div>                        
                    </div>
                </div>
            </div>
        </section>
      </main>
    </>
  )
}
