import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/descricao.module.css'
import LoginHeader from './components/loginheader'
import LogoDescricao from "./../public/images/image 5.svg"
import SetaParaBaixo from "./../public/images/setaparabaixo.svg"

export default function Home() {
  return (
    <>
      <Head>
        <title>AfroPunk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LoginHeader />
        <section className={styles.section}>
            <Image src={LogoDescricao} alt="" width={816} height={459} />
            <div className={styles.descricao}>
                <h1>DESCRIÇÃO DO EVENTO</h1>
                <div className={styles.paragrafos}>
                    <p>Na cidade mais negra fora da África, o reencontro com a ancestralidade: 
    apresentamos a terceira edição brasileira do maior festival de cultura negra do mundo.</p>
                    <p>É hora de celebrar sua comunidade! Sejam bem-vindes ao AFROPUNK Bahia 2023!...</p>
                </div>
                <div id={styles.linha}></div>
                <div id={styles.setabaixo}>                    
                    <a><Image src={SetaParaBaixo} alt="" width={44} height={24} /></a>
                </div>                
            </div>
            <div>
                <div className={styles.arena}>
                    <h2>Arena</h2>
                </div>
                <div className={styles.ingressos}>
                    <div className={styles.card}>
                        <p>Meia - EXCLUSIVE FOR STUDENT, ELDERLY, TRANS, PWD, TEACHER</p>
                        <p>R$ 85,00</p>
                        <a>BOTÕES</a>
                    </div>
                    <div className={styles.card}>
                        <p>MEIA SOCIAL - SOCIAL TICKET</p>
                        <p>R$ 95,00</p>
                        <a>BOTÕES</a>
                    </div>
                    <div className={styles.card}>
                        <p>Inteira</p>
                        <p>R$ 170,00</p>
                        <a>BOTÕES</a>
                    </div>
                </div>
                <div className={styles.subtotal}>
                    <h2>Subtotal: R$</h2>
                    {/* <h2>Subtotal: R$ {valor}</h2> */}
                    <a>Continuar</a>
                </div>
            </div>
        </section>
      </main>
    </>
  )
}
